[package]
name = "windows-capture"
version = "1.0.21"
authors = ["NiiightmareXD"]
edition = "2021"
description = "Simple Windows Screen Capture Library For Rust And Python 🔥"
documentation = "https://docs.rs/windows-capture"
readme = "README.md"
repository = "https://github.com/NiiightmareXD/windows-capture"
license = "MIT"
keywords = ["screen", "capture", "screenshot", "graphics", "windows"]
categories = [
    "os::windows-apis",
    "api-bindings",
    "graphics",
    "gui",
    "multimedia",
]

[dependencies]
image = "0.24.7"
log = "0.4.20"
parking_lot = "0.12.1"
rayon = "1.8.0"
thiserror = "1.0.49"
windows = { version = "0.51.1", features = [
    "Win32_System_WinRT_Graphics_Capture",
    "Win32_Graphics_Direct3D11",
    "Win32_Foundation",
    "Graphics_Capture",
    "Win32_System_WinRT_Direct3D11",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Gdi",
    "System",
    "Graphics_DirectX_Direct3D11",
    "Foundation_Metadata",
    "Win32_UI_HiDpi",
] }
